# Genetic Constitution of A Population

## Frequencies of genes(alleles) and genotypes

**Genotype frequencies**: the freuqncy of a particular genotype being its proportion or percentage among the individuals.

**Population**: in the genetic sense, a population is not just a group of individuals, but a breeding group; and the genetics of a population is concerned not only with the genetic constitution of the individuals but also with the transmission of the genes from one generation to the next.

**The genetic constitution of a population**, refering to the genes it carries, is described by the array of **gene(alleles) frequencies**; that is, by specification of the alleles present at every locus and the numbers or proportions of the different alleles at each locus.

|||Frequencies|
|:--|:--:|:--:|
|Genes(Alleles)|$A_1$|p|
||$A_2$|q|
|Genotypes|$A_1A_1$|P|
||$A_1A_2$|H|
||$A_2A_2$|Q|

- p + q =1
- P + H + Q = 1
- $p = P + \frac{1}{2}H$ and $q = Q+ \frac{1}{2}H$

### Mendelian variation in natural populations

- large effects vs small effects
- restriction fragment length polymorphisms, or RFLPs
- Microsatllite (or simple sequence repeat, SSR)
- polymorphic loci

### Causes of change

The agencies through which the genetic properties of a population may be changed are these:

- Population size
- Differences of fertility(繁殖能力) and viability(生存能力): selection
- Migration and mutation
- Mating system
  - random mating (or panmixia) means that any individual has an equal chance of mating with any other individual in the population.

## Hardy-Weinberg equilibrium

### The Hardy-Weinberg law

In a large random-mating population with no selection, mutation, or migration, the gene frequencies and the genotype frequenies are constant from generation to generation; and, furthermore, there is a simple relationship between the gene frequencies and the genotype frequencies. These properties of a population are derived from a theorem, or principle, known as the **Hardy-Weinberg law** after Hardy and Weinberg, who independently demonstrated them in 1908. A population with constant gene and genotype frequencies is said to be in **Hardy-Weinberg equilibrium**.

|||Frequencies|
|:--|:--:|:--:|
|Genes(Alleles)|$A_1$|p|
||$A_2$|q|
|Genotypes|$A_1A_1$|$p^2$|
||$A_1A_2$|$2pq$|
||$A_2A_2$|$q^2$|

Note: the relationship above refers to autosomal genes

Two additional conditions:

- genes segregate normally in gametogenesis
- gene frequencies are the same in males and females

Table 1.1 Steps of deduction in the proof of HWL, and the conditions that mst hold

|Step|Frequency| deduction from:to|Conditions|
|--------:|-------:|:-------:|:------:|
|0|gene(allele)|parents||
|1a|gene(allele)|all gametes|(1)Normal gene segregating|
||||(2)Equal fertility of parents|
|1b|gene(allele)|gametes forming zygotes|(3)Equal fertilizing capacity of gametes|
||||(4)Large population|
|2|genotype|zygotes|(5)Random mating|
||||(6)Equal gene freuqncies in male and female parents|
|3|genotype|progeny|(7)Equal viability|
|4|gene(allele)|progeny||

```{r, echo=FALSE}
p = seq(0,1,0.01)
plot(p, (1-p)^2, ylab = "genotype frequency", xlab="Gene Freuqncy of A2", main="Under HWE",type="l", col="blue")
lines(p, 2*p*(1-p), col="green")
lines(p, p^2, col="grey")
text(0.2,0.8,"A1A1")
text(0.5,0.45,"A1A2")
text(0.8,0.8,"A2A2")
```

Two important features:

- the maximum of heterozygote frequency is 50% when p = q = 0.5
- the rare allele occures predominantly in heterozygotes

### Applications of the Hardy-Weinberg law

- allele frequency
- freuqncy of "carriers"

For example, $A_2A_2$ is associated with a recessive phenotype, the $A_2$ allele frequency is q. So the normal heterozygotes frquency is 2q(1-q). The percent of heterozygotes among normal individuals is 

$$H' = \frac{2q(1-q)}{2q(1-q) + (1-q)^2} = \frac{2q}{1+q}$$
- Test of Hardy-Weinberg equilibrium

### Mating frequencies and another proof of the Hardy-Weinberg law

Table 1.3 Nine types of mating

||$A_1A_1$(P)|$A_1A_2$(H)|$A_2A_2$(Q)|
|:--:|:--:|:--:|:--:|
|$A_1A_1$(P)|$P^2$|PH|PQ|
|$A_1A_2$(H)|PH|$H^2$|HQ|
|$A_2A_2$(Q)|PQ|HQ|$Q^2$|

Table 1.4

|mating type|mating freuqncy|frequency $A_1A_1$|frequency $A_1A_2$|frequency $A_2A_2$|
|:--:|:--:|:--:|:--:|:--:|
|$A_1A_1 \times A_1A_1$|$P^2$|$P^2$|-|-|
|$A_1A_1 \times A_1A_2$|2PH|PH|PH|-|
|$A_1A_1 \times A_2A_2$|2PQ|-|2PQ|-|
|$A_1A_2 \times A_1A_2$|$H^2$|$\frac{1}{4}H^2$|$\frac{1}{4}H^2$|$\frac{1}{2}H^2$|
|$A_1A_2 \times A_2A_2$|2HQ|-|HQ|HQ|
|$A_2A_2 \times A_2A_2$|$Q^2$|-|-|$Q^2$|
||Sums|$p^2$|2pq|$q^2$|

### Multiple alleles

When there are more than 2 alleles at a locus, the genotype frequencies are determined by the gene(allele) frequencies in exactly the same way as with two alleles.

### Sex-linked genes

For homogametic sex (human females), gene and genotype frequency is the same as with the autosomal gene, but the heterogametic sex (human males) has only two genotypes and each individual carries only one gene instead of two.

So 2/3 (4 out of 6) sex-linked alleles are carried by females and 1/3 by males in the population.

Consider two alleles, A1 and A2, with frequencies p and q, and the genotypic frequencies as follow:

|||Frequencies|
|:--|:--:|:--:|
|Females|$A_1A_1$|P|
||$A_1A_2$|H|
||$A_2A_2$|Q|
|Males|$A_1$|R|
||$A_2$|S|

For females, the A1 frequncy $p_f = P + \frac{1}{2}H$; for males, the $p_m = R$, so the frequency of $A_1$ in the whole population is,

$$\bar{p} = \frac{2}{3}p_f + \frac{1}{3}p_m = \frac{1}{3}(2P + H + R)$$

### More than one locus

## Non-random mating

### Assortative mating